version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "eb:ef:ff:2d:5a:75:01:b5:cb:e6:fa:c5:01:e2:ef:93"
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn deploy
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy